#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker01"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d7aaaf0adafa4a22859ce71eeab367a0" }
]

[assets]
directory = "./public"
